### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by LucasCLuk** [avioli/uni_links#29]
I'm using https scheme and am testing
on my Samsung S4,
which is running Android 5.0.1.

I am getting: 
``MissingPluginException(No implementation found for method listen on channel uni_links/events)``

I get this when trying to call getLinksStream, getInitalLink or any uni_links platform method.

**Comment by pmundt** [comment]
I'm not sure that this is an issue with your version, or whether it is a problem with some of the tool versions. I've observed a similar crash running the same code on the same phone on two different machines - one works as advertised, while the other results in a crash as above. I suspect the culprit is a mismatch between versions of some of the platform tools, but I have not had the chance to dig into this further yet.

For reference, on the machine where this crashes, the full trace looks like:

```
I/SurfaceView(17753): updateWindow -- setFrame, this = io.flutter.view.FlutterView{150253a VFED..... .F...... 0,0-1080,1920}
I/flutter (17753): [2019-08-16 00:10:42.394599 | ConsoleHandler | INFO] ============================== CATCHER LOG ==============================
I/flutter (17753): [2019-08-16 00:10:42.395773 | ConsoleHandler | INFO] Crash occured on 2019-08-16 00:10:42.381866
I/flutter (17753): [2019-08-16 00:10:42.396399 | ConsoleHandler | INFO] 
I/flutter (17753): [2019-08-16 00:10:42.398669 | ConsoleHandler | INFO] ------- DEVICE INFO -------
I/flutter (17753): [2019-08-16 00:10:42.400619 | ConsoleHandler | INFO] 
I/flutter (17753): [2019-08-16 00:10:42.402541 | ConsoleHandler | INFO] ------- APP INFO -------
I/flutter (17753): [2019-08-16 00:10:42.403402 | ConsoleHandler | INFO] 
I/flutter (17753): [2019-08-16 00:10:42.403984 | ConsoleHandler | INFO] ---------- ERROR ----------
I/flutter (17753): [2019-08-16 00:10:42.404687 | ConsoleHandler | INFO] MissingPluginException(No implementation found for method getInitialLink on channel uni_links/messages)
I/flutter (17753): [2019-08-16 00:10:42.405322 | ConsoleHandler | INFO] 
I/flutter (17753): [2019-08-16 00:10:42.407067 | ConsoleHandler | INFO] ------- STACK TRACE -------
I/flutter (17753): [2019-08-16 00:10:42.411225 | ConsoleHandler | INFO] #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
I/flutter (17753): [2019-08-16 00:10:42.411786 | ConsoleHandler | INFO] <asynchronous suspension>
I/flutter (17753): [2019-08-16 00:10:42.412350 | ConsoleHandler | INFO] #1      getInitialLink (package:uni_links/uni_links.dart:18:46)
I/flutter (17753): [2019-08-16 00:10:42.412927 | ConsoleHandler | INFO] <asynchronous suspension>
I/flutter (17753): [2019-08-16 00:10:42.413639 | ConsoleHandler | INFO] #2      DeepLinksModel.initUniLinks (package:knowgo_car/models/deep_links.dart:27:34)
I/flutter (17753): [2019-08-16 00:10:42.414267 | ConsoleHandler | INFO] <asynchronous suspension>
I/flutter (17753): [2019-08-16 00:10:42.414877 | ConsoleHandler | INFO] #3      new DeepLinksModel._internal (package:knowgo_car/models/deep_links.dart:11:5)
I/flutter (17753): [2019-08-16 00:10:42.415405 | ConsoleHandler | INFO] #4      DeepLinksModel._deepLinksModel (package:knowgo_car/models/deep_links.dart:8:64)
I/flutter (17753): [2019-08-16 00:10:42.416026 | ConsoleHandler | INFO] #5      DeepLinksModel._deepLinksModel (package:knowgo_car/models/deep_links.dart:8:31)
I/flutter (17753): [2019-08-16 00:10:42.416545 | ConsoleHandler | INFO] #6      new DeepLinksModel (package:knowgo_car/models/deep_links.dart:15:12)
I/flutter (17753): [2019-08-16 00:10:42.417136 | ConsoleHandler | INFO] #7      KnowGoCarAppState.initState (package:knowgo_car/main.dart:92:23)
I/flutter (17753): [2019-08-16 00:10:42.417635 | ConsoleHandler | INFO] #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
I/flutter (17753): [2019-08-16 00:10:42.418294 | ConsoleHandler | INFO] #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (17753): [2019-08-16 00:10:42.418917 | ConsoleHandler | INFO] #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (17753): [2019-08-16 00:10:42.419517 | ConsoleHandler | INFO] #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (17753): [2019-08-16 00:10:42.420086 | ConsoleHandler | INFO] #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (17753): [2019-08-16 00:10:42.421116 | ConsoleHandler | INFO] #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (17753): [2019-08-16 00:10:42.421771 | ConsoleHandler | INFO] #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (17753): [2019-08-16 00:10:42.422360 | ConsoleHandler | INFO] #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (17753): [2019-08-16 00:10:42.423005 | ConsoleHandler | INFO] #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (17753): [2019-08-16 00:10:42.423531 | ConsoleHandler | INFO] #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (17753): [2019-08-16 00:10:42.424152 | ConsoleHandler | INFO] #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (17753): [2019-08-16 00:10:42.424716 | ConsoleHandler | INFO] #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (17753): [2019-08-16 00:10:42.425312 | ConsoleHandler | INFO] #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (17753): [2019-08-16 00:10:42.425918 | ConsoleHandler | INFO] #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (17753): [2019-08-16 00:10:42.426691 | ConsoleHandler | INFO] #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (17753): [2019-08-16 00:10:42.427497 | ConsoleHandler | INFO] #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (17753): [2019-08-16 00:10:42.428104 | ConsoleHandler | INFO] #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (17753): [2019-08-16 00:10:42.428694 | ConsoleHandler | INFO] #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (17753): [2019-08-16 00:10:42.429222 | ConsoleHandler | INFO] #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (17753): [2019-08-16 00:10:42.429854 | ConsoleHandler | INFO] #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter (17753): [2019-08-16 00:10:42.430476 | ConsoleHandler | INFO] #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (17753): [2019-08-16 00:10:42.431112 | ConsoleHandler | INFO] #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (17753): [2019-08-16 00:10:42.431719 | ConsoleHandler | INFO] #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (17753): [2019-08-16 00:10:42.432252 | ConsoleHandler | INFO] #31     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
I/flutter (17753): [2019-08-16 00:10:42.434213 | ConsoleHandler | INFO] #32     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:910:5)
I/flutter (17753): [2019-08-16 00:10:42.434839 | ConsoleHandler | INFO] #33     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:856:17)
I/flutter (17753): [2019-08-16 00:10:42.435664 | ConsoleHandler | INFO] #34     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter (17753): [2019-08-16 00:10:42.436624 | ConsoleHandler | INFO] #35     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:855:13)
I/flutter (17753): [2019-08-16 00:10:42.437188 | ConsoleHandler | INFO] #36     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter (17753): [2019-08-16 00:10:42.437850 | ConsoleHandler | INFO] #37     runApp (package:flutter/src/widgets/binding.dart:786:7)
I/flutter (17753): [2019-08-16 00:10:42.438457 | ConsoleHandler | INFO] #38     Catcher._setupErrorHooks.<anonymous closure> (package:catcher/core/catcher.dart:129:7)
I/flutter (17753): [2019-08-16 00:10:42.439053 | ConsoleHandler | INFO] #39     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
I/flutter (17753): [2019-08-16 00:10:42.439570 | ConsoleHandler | INFO] #40     Catcher._setupErrorHooks.<anonymous closure> (package:catcher/core/catcher.dart:128:14)
I/flutter (17753): [2019-08-16 00:10:42.440150 | ConsoleHandler | INFO] #41     _rootRun (dart:async/zone.dart:1124:13)
I/flutter (17753): [2019-08-16 00:10:42.440645 | ConsoleHandler | INFO] #42     _CustomZone.run (dart:async/zone.dart:1021:19)
I/flutter (17753): [2019-08-16 00:10:42.441211 | ConsoleHandler | INFO] #43     _runZoned (dart:async/zone.dart:1516:10)
I/flutter (17753): [2019-08-16 00:10:42.441665 | ConsoleHandler | INFO] #44     runZoned (dart:async/zone.dart:1500:12)
I/flutter (17753): [2019-08-16 00:10:42.442223 | ConsoleHandler | INFO] #45     Catcher._setupErrorHooks (package:catcher/core/catcher.dart:128:5)
I/flutter (17753): [2019-08-16 00:10:42.442769 | ConsoleHandler | INFO] #46     Catcher._configure (package:catcher/core/catcher.dart:55:5)
I/flutter (17753): [2019-08-16 00:10:42.443258 | ConsoleHandler | INFO] #47     new Catcher (package:catcher/core/catcher.dart:48:5)
I/flutter (17753): [2019-08-16 00:10:42.443861 | ConsoleHandler | INFO] #48     main (package:knowgo_car/main.dart:52:3)
I/flutter (17753): [2019-08-16 00:10:42.444541 | ConsoleHandler | INFO] #49     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
I/flutter (17753): [2019-08-16 00:10:42.445154 | ConsoleHandler | INFO] #50     _rootRunUnary (dart:async/zone.dart:1132:38)
I/flutter (17753): [2019-08-16 00:10:42.445693 | ConsoleHandler | INFO] #51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
I/flutter (17753): [2019-08-16 00:10:42.446330 | ConsoleHandler | INFO] #52     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
I/flutter (17753): [2019-08-16 00:10:42.446906 | ConsoleHandler | INFO] #53     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
I/flutter (17753): [2019-08-16 00:10:42.447439 | ConsoleHandler | INFO] #54     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
I/flutter (17753): [2019-08-16 00:10:42.447912 | ConsoleHandler | INFO] #55     Future._complete (dart:async/future_impl.dart:473:7)
I/flutter (17753): [2019-08-16 00:10:42.448537 | ConsoleHandler | INFO] #56     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
I/flutter (17753): [2019-08-16 00:10:42.449297 | ConsoleHandler | INFO] #57     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
I/flutter (17753): [2019-08-16 00:10:42.449859 | ConsoleHandler | INFO] #58     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
I/flutter (17753): [2019-08-16 00:10:42.451067 | ConsoleHandler | INFO] #59     availableCameras (package:camera/camera.dart)
I/flutter (17753): [2019-08-16 00:10:42.451662 | ConsoleHandler | INFO] #60     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
I/flutter (17753): [2019-08-16 00:10:42.452140 | ConsoleHandler | INFO] #61     _rootRunUnary (dart:async/zone.dart:1132:38)
I/flutter (17753): [2019-08-16 00:10:42.452721 | ConsoleHandler | INFO] #62     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
I/flutter (17753): [2019-08-16 00:10:42.453254 | ConsoleHandler | INFO] #63     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
I/flutter (17753): [2019-08-16 00:10:42.453901 | ConsoleHandler | INFO] #64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
I/flutter (17753): [2019-08-16 00:10:42.454780 | ConsoleHandler | INFO] #65     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
I/flutter (17753): [2019-08-16 00:10:42.455444 | ConsoleHandler | INFO] #66     Future._complete (dart:async/future_impl.dart:473:7)
I/flutter (17753): [2019-08-16 00:10:42.455985 | ConsoleHandler | INFO] #67     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
I/flutter (17753): [2019-08-16 00:10:42.456508 | ConsoleHandler | INFO] #68     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
I/flutter (17753): [2019-08-16 00:10:42.457038 | ConsoleHandler | INFO] #69     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
I/flutter (17753): [2019-08-16 00:10:42.457570 | ConsoleHandler | INFO] #70     MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart)
I/flutter (17753): [2019-08-16 00:10:42.458128 | ConsoleHandler | INFO] #71     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
I/flutter (17753): [2019-08-16 00:10:42.458767 | ConsoleHandler | INFO] #72     _rootRunUnary (dart:async/zone.dart:1132:38)
I/flutter (17753): [2019-08-16 00:10:42.459252 | ConsoleHandler | INFO] #73     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
I/flutter (17753): [2019-08-16 00:10:42.459826 | ConsoleHandler | INFO] #74     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
I/flutter (17753): [2019-08-16 00:10:42.460384 | ConsoleHandler | INFO] #75     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
I/flutter (17753): [2019-08-16 00:10:42.460947 | ConsoleHandler | INFO] #76     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
I/flutter (17753): [2019-08-16 00:10:42.461560 | ConsoleHandler | INFO] #77     Future._complete (dart:async/future_impl.dart:473:7)
I/flutter (17753): [2019-08-16 00:10:42.462187 | ConsoleHandler | INFO] #78     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
I/flutter (17753): [2019-08-16 00:10:42.462749 | ConsoleHandler | INFO] #79     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
I/flutter (17753): [2019-08-16 00:10:42.463392 | ConsoleHandler | INFO] #80     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
I/flutter (17753): [2019-08-16 00:10:42.463933 | ConsoleHandler | INFO] #81     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
I/flutter (17753): [2019-08-16 00:10:42.464534 | ConsoleHandler | INFO] #82     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
I/flutter (17753): [2019-08-16 00:10:42.465206 | ConsoleHandler | INFO] #83     _rootRunUnary (dart:async/zone.dart:1132:38)
I/flutter (17753): [2019-08-16 00:10:42.466056 | ConsoleHandler | INFO] #84     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
I/flutter (17753): [2019-08-16 00:10:42.466776 | ConsoleHandler | INFO] #85     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
I/flutter (17753): [2019-08-16 00:10:42.467320 | ConsoleHandler | INFO] #86     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
I/flutter (17753): [2019-08-16 00:10:42.467962 | ConsoleHandler | INFO] #87     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
I/flutter (17753): [2019-08-16 00:10:42.468507 | ConsoleHandler | INFO] #88     Future._completeWithValue (dart:async/future_impl.dart:483:5)
I/flutter (17753): [2019-08-16 00:10:42.469127 | ConsoleHandler | INFO] #89     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
I/flutter (17753): [2019-08-16 00:10:42.470391 | ConsoleHandler | INFO] #90     _rootRun (dart:async/zone.dart:1124:13)
I/flutter (17753): [2019-08-16 00:10:42.470960 | ConsoleHandler | INFO] #91     _CustomZone.run (dart:async/zone.dart:1021:19)
I/flutter (17753): [2019-08-16 00:10:42.471444 | ConsoleHandler | INFO] #92     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
I/flutter (17753): [2019-08-16 00:10:42.471917 | ConsoleHandler | INFO] #93     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
I/flutter (17753): [2019-08-16 00:10:42.472567 | ConsoleHandler | INFO] #94     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
I/flutter (17753): [2019-08-16 00:10:42.472992 | ConsoleHandler | INFO] #95     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/flutter (17753): [2019-08-16 00:10:42.473385 | ConsoleHandler | INFO] 
I/flutter (17753): [2019-08-16 00:10:42.474374 | ConsoleHandler | INFO] ======================================================================
```

**Comment by djsliders** [comment]
Any updates?

**Comment by markathomas** [comment]
Same issue.  This happened after upgrade to Flutter v1.12.13+hotfix.6

**Comment by markathomas** [comment]
Any chance we could get this resolved?  It's blocking my upgrade to 1.12.  Be happy to send a donation...

**Comment by Zazo032** [comment]
This is also happening to me, after upgrading to latest Flutter version and migrating the app to [Android V2 Embedding](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects). Any chance you can look into this @avioli?

**Comment by Zazo032** [comment]
```
I/flutter ( 7906): MissingPluginException(No implementation found for method getInitialLink on channel uni_links/messages)
```

**Comment by markathomas** [comment]
All, I have a working version in my private pub repo but you can view the PR at https://github.com/avioli/uni_links/pull/55 or fork my version at https://github.com/markathomas/uni_links

**Comment by geek-sajjad** [comment]
hello i have this problem too ! 



> E/flutter ( 1091): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getInitialLink on channel uni_links/messages)
E/flutter ( 1091): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 1091): <asynchronous suspension>
E/flutter ( 1091): #1      getInitialLink (package:uni_links/uni_links.dart:18:46)
E/flutter ( 1091): #2      _PlansScreenState.initUniLinks (package:vpn_surf/pages/plans/plans_screen.dart:45:34)
E/flutter ( 1091): #3      _PlansScreenState.initState (package:vpn_surf/pages/plans/plans_screen.dart:60:5)
E/flutter ( 1091): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter ( 1091): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 1091): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 1091): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 1091): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 1091): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 1091): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 1091): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 1091): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 1091): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 1091): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 1091): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 1091): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 1091): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 1091): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 1091): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 1091): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 1091): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 1091): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 1091): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 1091): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 1091): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 1091): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter ( 1091): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 1091): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 1091): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 1091): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 1091): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 1091): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 1091): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 1091): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 1091): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 1091): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 1091): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 1091): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 1091): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter ( 1091): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 1091): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 1091): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 1091): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 1091): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 1091): #45     ComponentEle

> Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (4 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

**Comment by heidji** [comment]
Yeah, I'm getting this when I use the flutter_facebook_login package.

**Comment by heidji** [comment]
I managed to fix it by completely removing the flutter_google_ad_manager plugin AND its references in the manifest.
maybe this helps someone

**Comment by ZaifSenpai** [comment]
I am having same issue. I think it is because of the [flutter_stripe](https://pub.dev/packages/flutter_stripe) library I am using. because this problem started occurring after I have installed flutter_stripe.

I hate it when there is a dependency problem between 2 important libraries.

**Comment by ZaifSenpai** [comment]
Hi everyone. For me, this problem was occurring due to the older version of Kotlin because I was trying to use [flutter_stripe](https://pub.dev/packages/flutter_stripe) and it was using a newer version of Kotlin. So I updated Kotlin like following steps and it worked:

#### 1. Update Kotling version
#### Open \android\build.gradle and update kotlin version. Latest is v1.5.10 atm. Checked latest version [here](https://kotlinlang.org/docs/releases.html#release-details)
```
buildscript {
    ext.kotlin_version = '1.5.10'
    ....
}
```

#### 2. make sure that the following file exists. If it does not, then `flutter clean`, `flutter pub get` and build your app
```
\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
```

#### 3. Then open MainActivity.kt and _configureFlutterEngine_ like this:
```
package ...

import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.EventChannel
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity : FlutterFragmentActivity() {
    private val CHANNEL = "getEpubs"
    var _eventSink: EventChannel.EventSink? = null

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}

```
#### 4. You may also want to update gradle version at
```
\android\gradle\wrapper\gradle-wrapper.properties
```
Mine is `gradle-6.9-all.zip`



I hope this helps.

**Comment by leonx98** [comment]
Having the same issue, but didn't find a solution yet...
